." Manpage for sudoku.
." Contact nwang <nwang@novell.com> to correct errors or typos.
.TH man 6 "25 AUG 2011" "1.0" "sudoku"
.SH NAME
sudoku
.SH SYNOPSIS
/usr/sbin/shudoku
.SH TYPE
Game.
.SH DESCRIPTION
A solution of Sudoku.
.br
Scripts are written in C++.
.SH README
None. 
.SH OPTIONS
None
.SH WHAT IT DOES
/usr/sbin/shudoku will run.
.br
A solution of Sudoku.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. No licence provided in the sources. Internal development. Meant to be GPL.
.SH LICENSE
License: n/a. Spec file license: GPL.
.SH UPSTREAM
http://qa.suse.de
.SH AUTHOR
nwang <nwang@novell.com>
.SH MAINTAINER
nwang <nwang@novell.com>
